name: MDXCanvas Publish

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write

jobs:
  mdxcanvas_publish:
    uses: BYU-CS-Course-Ops/utils/.github/workflows/poetry_publish.yaml@main
    with:
      pypi_package: "mdxcanvas"
    secrets:
      discord_webhook_url: ${{ secrets.GHA_DISCORD_WEBHOOK }}
      discord_role: ${{ secrets.CICD_NOTIFY_DISCORD_ROLE }}
