name: pypi_build_and_publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [merged]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: |
          pip install poetry

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_USERNAME: ${{ secrets.PYPI_USER }}
          POETRY_PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: poetry publish --username $POETRY_PYPI_USERNAME --password $POETRY_PYPI_PASSWORD